spring:
  application:
    name: kotlin-delivery-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    mode: native
    embedded:
      queues: test
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8082

mail:
  imap:
    ssl: true
    host: imap.gmail.com
    port: 993
    username:
    password:


artemis: "test"

